name: ðŸš€ Release MacOS

on:
  workflow_call:
    inputs:
      PYTHON_VERSIONS:
        description: "Python versions to build"
        required: true
        type: string

env:
  MACOSX_DEPLOYMENT_TARGET: 10.13

jobs:
  release_macos:
    name: Release Oxen MacOS
    runs-on: macos-15-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release directory
        run: mkdir ${{ github.workspace }}/release

      - name: Install latest rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build oxen binaries
        run: |
          cd ${{ github.workspace }}/oxen-rust

          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

          cargo build --release --target aarch64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Build Python wheels
        run: |
          uv python install ${{ inputs.PYTHON_VERSIONS }}

          cd ${{ github.workspace }}/oxen-python

          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

          for version in ${{ inputs.PYTHON_VERSIONS }}; do
            uvx maturin build --release --interpreter /Users/runner/.local/bin/python${version} --target aarch64-apple-darwin
            uvx maturin build --release --interpreter /Users/runner/.local/bin/python${version} --target x86_64-apple-darwin
          done

      - name: Create tarballs with oxen binaries
        run: |
          tar -czvf ${{ github.workspace }}/release/oxen-macos-arm64.tar.gz -C ${{ github.workspace }}/oxen-rust/target/aarch64-apple-darwin/release/ oxen
          tar -czvf ${{ github.workspace }}/release/oxen-macos-x86_64.tar.gz -C ${{ github.workspace }}/oxen-rust/target/x86_64-apple-darwin/release/ oxen
          tar -czvf ${{ github.workspace }}/release/oxen-server-macos-arm64.tar.gz -C ${{ github.workspace }}/oxen-rust/target/aarch64-apple-darwin/release/ oxen-server
          tar -czvf ${{ github.workspace }}/release/oxen-server-macos-x86_64.tar.gz -C ${{ github.workspace }}/oxen-rust/target/x86_64-apple-darwin/release/ oxen-server

      - name: Create tarballs with Python wheels
        run: |
          cd ${{ github.workspace }}/oxen-python/target/wheels/

          tar -czvf ${{ github.workspace }}/release/oxen-wheels-macos-x86_64.tar.gz ./*x86_64.whl
          tar -czvf ${{ github.workspace }}/release/oxen-wheels-macos-arm64.tar.gz ./*arm64.whl

      - name: Create tarball with all artifacts
        run: |
          tar -czvf ${{ github.workspace }}/oxen-macos-release.tar.gz -C ${{ github.workspace }}/release/ .

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oxen-macos-release.tar.gz
          path: ${{ github.workspace }}/oxen-macos-release.tar.gz
          retention-days: 1